apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fincontrol-back.fullname" . }}-config
  labels:
    {{- include "fincontrol-back.labels" . | nindent 4 }}
data:
  PORT: "8080"
  ENV: {{ .Values.config.env | quote }}
  DB_HOST: {{ .Values.config.dbHost | quote }}
  DB_PORT: {{ .Values.config.dbPort | quote }}
  DB_NAME: {{ .Values.config.dbName | quote }}
  DB_SSL_MODE: {{ .Values.config.dbSslMode | quote }}
  CORS_ORIGIN: {{ .Values.config.corsOrigin | quote }}
