version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - gofmt
    - gosec
    - noctx
  settings:
    gosec:
      excludes:
        - G115
