version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - gosec
    - noctx
  settings:
    gosec:
      excludes:
        - G115

formatters:
  enable:
    - gofmt
